void affichageStats(Partie partieEnCours) ;
int menu(int nbreChoix);
int compteTouche(int touche, int secondesMax);
void chargementSauvegarde(FILE* sauvegarde, Partie* partieEnCours);
void sauvegarde(Partie partieEnCours);
int lancerDeDes(Partie* partieEnCours);
void deplacementPlateau(int choix, Partie* partieEnCours);
void recit(char ecrit[300]);
void experiencePlus(Partie* partieEnCours, int experienceBonus);
void proute(int choix);
